export const FIND_REVIEWEES = "FIND_REVIEWEES";
export const CLEAR_REVIEWEES = "CLEAR_REVIEWEES";
export const LOAD_REVIEWEES = "LOAD_REVIEWEES";
export const SORT_REVIEWEES = "SORT_REVIEWEES";

export const FIND_SCHOOLS = "FIND_SCHOOLS";
export const CLEAR_SCHOOLS = "CLEAR_SCHOOLS";
export const LOAD_SCHOOLS = "LOAD_SCHOOLS";

export const GET_REVIEWS = "GET_REVIEWS";
export const ADD_REVIEW = "ADD_REVIEW";
export const VOTE = "VOTE"
export const REPORT_INAPPROPRIATE_REVIEW = "REPORT_INAPPROPRIATE_REVIEW";

export const RESEND_VERIFICATION = "RESEND_VERIFICATION";

export const SET_ERROR = "SET_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_SUCCESS = "SET_SUCCESS";
export const REMOVE_SUCCESS = "REMOVE_SUCCESS";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const SET_LOADING = "SET_LOADING";
export const REMOVE_LOADING = "REMOVE_LOADING";

export const CHANGE_IS_MOBILE = "CHANGE_IS_MOBILE";

